[colors.bright]
black = "#000000"
red = "#d70000"
green = "#00ff00"
yellow = "#ffd700"
blue = "#5f87ff"
magenta = "#ff5fff"
cyan = "#5fffff"
white = "#ffffff"
# black = "#676767"
# red = "#ff6d67"
# green = "#5ff967"
# yellow = "#fefb67"
# blue = "#6871ff"
# magenta = "#ff76ff"
# cyan = "#5ffdff"
# white = "#fffeff"

[colors.cursor]
cursor = "#c7c7c7"
text = "#fffeff"

# [colors.normal]
# black = "#000000"
# red = "#d70000"
# green = "#00ff00"
# yellow = "#ffff00"
# blue = "#5f87ff"
# magenta = "#ff5fff"
# cyan = "#5fffff"
# white = "#ffffff"

# blue = "#00afff"
# 075: #5fafff
# 057: #5f00ff

[colors.normal]
black = "#676767"
red = "#ff6d67"
green = "#5ff967"
yellow = "#fefb67"
blue = "#6871ff"
magenta = "#ff76ff"
cyan = "#5ffdff"
white = "#fffeff"

# black = "#000000"
# red = "#c91b00"
# green = "#00c200"
# yellow = "#c7c400"
# blue = "#0225c7"
# magenta = "#c930c7"
# cyan = "#00c5c7"
# white = "#c7c7c7"

[colors.primary]
background = "#000000"
foreground = "#c7c7c7"

[cursor.style]
blinking = "Never"

[env]
TERM = "screen-256color"
# TERM = "xterm-256color"
# enable_rgb="true"

[font]
# ligatures = true
size = 14.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Nerd Font"
style = "Light Oblique"

[font.normal]
family = "Iosevka Nerd Font"
style = "None"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
dynamic_title = true
decorations = "Buttonless"
# history = 10000
# live_config_reload = true
# save_to_clipboard = true
# semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window.padding]
x = 6
y = 6

[mouse]
hide_when_typing = true




