require("TargetFile").setup({
  supported_languages = {
    ['.cpp'] = {
      name = 'C++',
      ext = '.cpp',
      compile_cmd = 'g++ -g -Wshadow -Wall -Wextra --std=c++20 %fp -o %fben',
      execute_cmd = '%fben',
      debug_cmd = nil,
      debut_window_cmd = nil,
      -- debug_cmd = 'gdb -tui %fben',
      -- debut_window_cmd = 'tabe | set nowrap | startinsert | term ',
    },
    ['.c'] = {
      name = 'C',
      ext = '.c',
      compile_cmd = 'gcc -g -Wshadow -Wall -Wextra -std=c99 %fp -o %fben',
      execute_cmd = '%fben',
      debug_cmd = nil,
      debut_window_cmd = nil,
      -- debug_cmd = 'gdb -tui %fben',
      -- debut_window_cmd = 'tabe | set nowrap | startinsert | term ',
    },
    ['.rs'] = {
      name = 'Rust',
      ext = '.rs',
      compile_cmd = 'rustc %fp',
      execute_cmd = '%fen',
      debug_cmd = nil,
      debut_window_cmd = nil,
      -- debug_cmd = 'gdb -tui %fben',
      -- debut_window_cmd = 'tabe | set nowrap | startinsert | term ',
    },
    ['.java'] = {
      name = 'Java',
      ext = '.java',
      compile_cmd = 'javac -d %fdb %fp',
      execute_cmd = 'java -cp %fdb %fp',
      debug_cmd = nil,
      debut_window_cmd = nil,
    },
    ['.js'] = {
      name = 'Javascript',
      ext = '.js',
      compile_cmd = nil,
      execute_cmd = 'node %fp',
      debug_cmd = nil,
      debut_window_cmd = nil,
    },
  },
})
